### ISSUE TITLE
Add Fuse driver

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/libstorage#189]
This issue tracks the addition of the Fuse driver.

The Fuse driver would enable any Fuse compatible storage provider would work with libStroage. This would include things like S3 object stores.

**Comment by kasisnu** [comment]
Hi,

It looks like this work might depend on being able to pass custom mount options from storage drivers through to os drivers. Currently, it looks like the docker integration driver ignores them entirely - https://github.com/emccode/libstorage/blob/master/drivers/integration/docker/docker.go#L294.

Is there any wip on this issue?

Additionally, I think(incorrectly?) the idea behind storage drivers was that they shouldn't concern themselves with platform-specific code, in which case maybe the storage drivers shouldn't be required to provide these, but some abstraction is still needed since fuse drivers usually accept additional options outside of mount src/targets.

Thoughts?

**Comment by vaibhavkhanduja** [comment]
I suppose, unless there a new implementation own fuse driver, supporting all in one single abstraction may be tough. The abstraction to the backend storage gets hidden behind the the fuse (possibly?). For objects stores supporting S3 like api's there are some implementations available (https://github.com/s3ql/s3ql). For others, libquestfs (http://libguestfs.org/guestfs-faq.1.html) could be an option - OSX and Linux.

**Comment by vaibhavkhanduja** [comment]
@clintonskitson @akutz any thoughts here?

**Comment by clintonskitson** [comment]
Wish I had more for you, deferring to @akutz here.

**Comment by kacole2** [comment]
#397 is PRd

**Comment by codenrhoden** [comment]
I think it's worth exploring whether a generic FUSE driver is possible, echoing what @vaibhavkhanduja said. And as @kacole2 points out, support for S3 over FUSE went in with #397, which uses s3fs. If it really comes down to drivers for specific integrations, this can probably be closed.
