### ISSUE TITLE
libStorage API volumeInspect route should work in one consistent way

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/libstorage#311]
According to the [API doc](http://docs.libstorage.apiary.io/#reference/volumes/volume-inspector/get), an API call to route `volumeInspect` does not support parameter `attachments`.  However,  the only way to retrieve full attachment information (including device name) is to provide the `attachments boolean parameter` (see output below).

Route `volumeInspect` should require both `Libstorage-Instanceid` and `Libstorage-Localdevices` headers and return all pertinent volume and attachment information for the specified volume id.   Today this is optional and it can be confusing.

The `volumeInspect` route supports the following three calls (at least with the `virtualbox` driver).  

_No local devices sent_

```
> curl -H "Libstorage-Instanceid: virtualbox=ca72be20-3cba-4bf9-842f-806729142d95" -X GET http://localhost:7979/volumes/virtualbox/af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0
{
  "attachments": [
    {
      "deviceName": "",
      "instanceID": {
        "id": "ca72be20-3cba-4bf9-842f-806729142d95",
        "driver": "virtualbox"
      },
      "status": "/Users/*****/VirtualBox Volumes/vol-0001",
      "volumeID": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0"
    }
  ],
  "name": "vol-0001",
  "size": 1,
  "status": "/Users/****/VirtualBox Volumes/vol-0001",
  "id": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0",
  "type": ""
}
```

_Local devices sent without attachments param_
 Notice,  the device name field not populated

```
> curl -H "Libstorage-Instanceid: virtualbox=ca72be20-3cba-4bf9-842f-806729142d95" -H "Libstorage-Localdevices: virtualbox=75dca810::/dev/sda5,af039ac8::/dev/sdb" -X GET http://localhost:7979/volumes/virtualbox/af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0
{
  "attachments": [
    {
      "deviceName": "",
      "instanceID": {
        "id": "ca72be20-3cba-4bf9-842f-806729142d95",
        "driver": "virtualbox"
      },
      "status": "/Users/*****/VirtualBox Volumes/vol-0001",
      "volumeID": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0"
    }
  ],
  "name": "vol-0001",
  "size": 1,
  "status": "/Users/*****/VirtualBox Volumes/vol-0001",
  "id": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0",
  "type": ""
}
```

_Both instanceid and localdevices header provided + plus the attachments param_

```
> curl -H "Libstorage-Instanceid: virtualbox=ca72be20-3cba-4bf9-842f-806729142d95" -H "Libstorage-Localdevices: virtualbox=75dca810::/dev/sda5,af039ac8::/dev/sdb" -X GET http://localhost:7979/volumes/virtualbox/af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0?attachments=true
{
  "attachments": [
    {
      "deviceName": "/dev/sdb",
      "instanceID": {
        "id": "ca72be20-3cba-4bf9-842f-806729142d95",
        "driver": "virtualbox"
      },
      "status": "/Users/*****/VirtualBox Volumes/vol-0001",
      "volumeID": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0"
    }
  ],
  "name": "vol-0001",
  "size": 1,
  "status": "/Users/****/VirtualBox Volumes/vol-0001",
  "id": "af039ac8-dc2b-4bdd-ba6a-81075fe3d7d0",
  "type": ""
}
```

Environment

```
Driver=virtuabox
> ./lss-linux --version
Binary: /home/*****/DEV/go/bin/lss-linux
SemVer: 0.3.1
OsArch: Linux-x86_64
Branch: (HEAD detached from 5cb6951
Commit: a3a561a1b94bb8b7efb4ae998540c457deb39692
Formed: Fri, 28 Oct 2016 13:57:27 EDT
```

**Comment by akutz** [comment]
Hi @vladimirvivien,

The API doesn't say it doesn't support it but rather states:

> If the libStorage-InstanceID header is provided the volume's attachments are also retrieved. Unlike when retrieving Volume collections, there's *no need* to specify the attachments query parameter to request their retrieval.

There's no need because the inclusion of the instance ID sets the implicit assumption that the attachment information is requested.

However, to your assertion at hand -- that there should be some consistent manner that the API should work.

Well, no. There kind of shouldn't. Or rather there kind of isn't a way to enforce it. It's up to the drivers to behave a way that is consistent with the API. For example, I discovered that the EBS storage driver is returning attachments when the instance ID is present regardless of whether the attachment flag is set to true. This caused me to make a bad judgement as to what was occurring for all drivers.

I agree with you in principle, but in practice it's up to the drivers to act as the API advises them to do.

Also, FWIW, I need to update the documentation to which you linked. I've been the only primary on the project for so long, and I haven't had the bandwidth to evolve the project and keep the public contract in sync with the actual implementation due to release pressures.

**Comment by akutz** [comment]
By the way @vladimirvivien, the API docs definitely need to be updated WRT the libStorage headers. The API docs are terribly out of date in that regard. Thank you for bringing this to my attention.

**Comment by vladimirvivien** [comment]
@akutz thanks for the quick reply.  But, when I think of the `volumeInspect` I think of a call that should return all pertinent info about the volume including its attachments data.  Now, if the driver can't fulfill all of the data, that's OK, but at least the API should mandate it.  

Route `volumes` is better suited for optional fields since you can be in a situation where a storage backend may return a large amount of data.  There, making attachment optionals makes sense because you could alleviate latency by leaving out attachment info (at least that's how it rings in my head).

Anyway,  I also noticed that the new rexray cli leaves out device path info (Driver=virtualbox) when a `rexray volume get <volumeid>` is done.  That may be due to this issue of consistently returning all pertinent fields, including attachments, by default.

**Comment by akutz** [comment]
Hi @vladimirvivien,

> when I think of the volumeInspect I think of a call that should return all pertinent info about the volume including its attachments data. Now, if the driver can't fulfill all of the data, that's OK, but at least the API should mandate it (not the other way around).

I totally agree. So you know, the reasoning is that gathering the attachment data requires additional calls on the back-end for some drivers, hence the option to do it or not. But I totally see your point and agree about the distinction  between inspecting a single volume and multiple volumes.

The new CLI returns that information, but it is not part of the default output format. Please file an enhancement request so that it is shown if present. Thanks!

**Comment by codenrhoden** [comment]
I'm following along here, and one thing confused me:

> The API doesn't say it doesn't support it but rather states:
> 
> > If the libStorage-InstanceID header is provided the volume's attachments are also retrieved. Unlike when retrieving Volume collections, there's no need to specify the attachments query parameter to request their retrieval.

...

> It's up to the drivers to behave a way that is consistent with the API. For example, I discovered that the EBS storage driver is returning attachments when the instance ID is present regardless of whether the attachment flag is set to true. This caused me to make a bad judgement as to what was occurring for all drivers.

According to the API, isn't that what the EBS driver is supposed to do? Or is the EBS comment referring to route `volumes` instead of `volumeInspect`?  Reading through a second time, I think that may be the case, but I wanted to double-check.

**Comment by akutz** [comment]
Hi @codenrhoden,

So the `attachments` flag has a few meanings as I'm remembering this morning. The original purpose of the `attachments` flag was to tell drivers they didn't have to return attachment data (unless flag was present and with a positive truthiness). However, somewhere along the line the flag got overloaded. See [this](https://github.com/codedellemc/rexray/pull/615#issuecomment-257312062) other discussion for an example.

Ultimately I will be replacing the flag with an enum. While it will be backwards compatible, `attachments` will also support something like the following:

Value | Description
---|------------
0 | No attachments requested
1 | Attachments requested
2 | "My" attachments requested (only attachments attached to the client that matches the provided instance ID)

Right now drivers are doing one of the following:

* Always returning attachments, regardless of the flag
* Returning attachments only if the flag is present
* Returning attachments attached to the client if the flag is present

And unfortunately the server route is stripping all attachments not attached to the client if the flag is present anyway, meaning you cannot get attachment information about other instances if the flag is set to `true`. However, since some drivers only return attachment information if the flag is true, there is no consistency.

Ultimately this is one of the reasons it's a good thing all drivers are in a single-repo to which we have access. I'm able to update them all according to new logic at once.

**Comment by codenrhoden** [comment]
The way we handle volume Attachments was great modified (enhanced!) in #316, #319, and #327. I think this can be closed.
