### ISSUE TITLE
Ineffectual mount label. What are the effects?

### ISSUE THREAD

**Issue by akutz** [codedellemc/libstorage#400]
Hi @codenrhoden / @cduchesne,

When working on PR #397 I noticed that [line \#101](https://github.com/codedellemc/libstorage/blob/master/drivers/os/linux/linux.go#L101-L102) in the OS driver `linux.go` is ineffectual. It means that the value is never used. Let's look at lines 101 and 102:

```go
	options := formatMountLabel("", opts.MountLabel)
	options = fmt.Sprintf("%s,%s", opts.MountOptions, opts.MountLabel)
```

The first value is never used because it's immediately overridden with the second. Now, the issue is that I'm not sure what the correct resolution is. Clearly what's there is what is working, so perhaps I *could* just remove the first line. However, what was the original intention? I need to look into it more. This issue is a reminder to do that as well as me asking you two to take a look as well. Thanks!

**Comment by codenrhoden** [comment]
Hell, it looks worse than that to me:

```
	options := formatMountLabel("", opts.MountLabel)
	options = fmt.Sprintf("%s,%s", opts.MountOptions, opts.MountLabel)
	if fsType == "xfs" {
		options = fmt.Sprintf("%s,nouuid", opts.MountLabel)
	}
```

If you specify a mount label, it's not going to be applied, since options is overwritten on the second line. But, if you *do* specify a mountlabel, I think that `fmt.Sprintf` line is going to spit out an invalid format for the mount command. it doens't have the `context=` key in front of it...

But the *other* thing is in the XFS block. All the mount options are lost for XFS (unless this was done on purpose?) becaues that `fmt.Sprintf` passes `opts.MountLabel` instead of `options`...

Just a first glance at it... I need to take another look at the diff between `mount -t xfs` and `mount -t ext3` and see if options and labels are handled correctly I guess.
