### ISSUE TITLE
Add callback functionality from server to client

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/libstorage#64]
Having a server be able to proactively call a client back to perform certain operations could be useful in certain opertational models.

Today the events all occur starting from a libstorage client or endpoint. This results in the libstorage client being delivered a mount point to be able to use.

If someone wishes to integrate storage services into a self provisioning portal, it could be helpful if the libStorage server was able to initiate callbacks of some form to the client. Today the requests to create/remove/attach/detach are all things that can be handled via libStorage server without explicitly running client activities on the endpoint. The mount/unmount which would be host level functions that occur in conjunction with the attach/detaches require that the host perform certain operations. If a remote service or self service portal wants to invoke from libStorage mount/unmount this would likely take place via libStorage server contacting the executor service via callback to perform those functions. Plenty of options to explore here.

Could this be the executor model changing? Could it be that the executor extends to something that actually runs persistently to ensure callback functionality?

Is it something that should be covered having another tools initiate the client events on the endpoint system?

**Comment by akutz** [comment]
Hi @clintonskitson,

Please add clarification to this ask as the obvious solution to the problem is something that had been discussed and suggested as an initial approach to what became the executor model -- a persistent, lightweight client service that is able to communicate with the server bidirectionally using an encrypted GRPC session. Unfortunately the approach was rejected, due to, I believe, an improper and/or incomplete examination. Long-term project plans such as these need to be vetted more vigorously upon initial review as these types of architectural decision have great cost to time and and resources when not given the proper consideration only to be reintroduced into the mix at a later date.

**Comment by clintonskitson** [comment]
I hear what you're saying here. I do believe architecturally you are on the right path today with executors. Let's flush this ask out soon.

**Comment by codenrhoden** [comment]
I'd be curious to hear updated thoughts on this. I think many use cases have come up that could benefit from this type of communication.
